name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # 1. Checkout project code
      # ------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------
      # 2. Setup JDK (Java 17)
      # ------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ------------------------
      # 3. Build Spring Boot JAR
      # ------------------------
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # ------------------------
      # 4. Deploy JAR to server
      # ------------------------
      # Equivalent to manual step:
      #   - Drag & drop JAR via SFTP to: /home/ubuntu/UravugalBackend
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}      # e.g., 3.108.40.49
          username: ${{ secrets.SERVER_USER }}  # e.g., ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}    # SSH private key
          source: "target/*.jar"
          target: "/home/ubuntu/UravugalBackend"

      # ------------------------
      # 5. Restart Spring Boot app on server
      # ------------------------
      # Equivalent to manual steps:
      #   - lsof -t -i 9100
      #   - sudo kill -9 <PID>
      #   - nohup java -jar matrimony-0.0.1-SNAPSHOT.jar 1> logger.log &
      #   - tail -f logger.log
      - name: Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Kill process running on port 9100 if exists
            PID=$(lsof -t -i:9100 || true)
            if [ -n "$PID" ]; then
              echo "Killing process on port 9100: $PID"
              sudo kill -9 $PID
            fi

            # Start new Spring Boot JAR
            cd /home/ubuntu/UravugalBackend
            nohup java -jar matrimony-0.0.1-SNAPSHOT.jar 1> logger.log 2>&1 &

            # Tail last 20 lines of log (for CI/CD visibility)
            tail -n 20 logger.log
